### ISSUE TITLE
r80+ Inline layer rules not extracted for view

### ISSUE THREAD

**Issue by littlejob** [CheckPointSW/ShowPolicyPackage#10]
Running this tool on any r80 gateway, or management server will not query, nor extract for view, any inline rule defined in a specific policy set. One would assume this would extract all policy contents, but that does not appear to be the case. 

Is this a future item that will be added? Would be ever so convenient..

**Comment by chkp-rdecker** [comment]
Hi,
The tool can not be run on a gateway, management server is ok, or on any linux or windows machine with Java >= 8 installed.
What do you mean by "inline rule"? Rules inside an inline layer?

**Comment by littlejob** [comment]
I shall rephrase and be more specific. When running the tool on a management server, specifying a particular policy with child firewall rules, those child rules (in-line), are not represented in the html web visualization. So you have the parent rule (rule #1) then you have the child rule (1.1, 1.2, 1.3), then you have the next parent rule (rule #2) lets say... and so on.. 

It is these "child rules" that are not represented in the web export using this showpolicypackage tool. 

I found it interesting, as they are indeed shown if you simply perform an export from the smart console GUI to a csv, but then there is no linkage to objects, and what hosts are defined in those objects created.

**Comment by chkp-rdecker** [comment]
Hi, the inline rules are there - in the "Action" column there is a link - 
![layer](https://user-images.githubusercontent.com/26377847/42928519-3116f8dc-8b40-11e8-8353-4cf928ace6ff.png)

click on it -
![inline](https://user-images.githubusercontent.com/26377847/42928600-6c8beddc-8b40-11e8-9db5-9c75a01fafba.png)

and there you are!

**Comment by littlejob** [comment]
Please see my attached screenshot. This _Action_ column does not represent a clickable link as shown in your screenshots. Below will show you what the CSV export looks like, compared to the web report shown using this tool.. 

![1](https://user-images.githubusercontent.com/3580651/42944086-b3a8d936-8b32-11e8-98df-fbca05a6f64b.png)

**Comment by chkp-rdecker** [comment]
Strange that there are no clickable links...
Are you using the latest version of the tool (v2.0.1)?
Can you paste here the complete command that you are using to run the tool?

**Comment by littlejob** [comment]
Ah, there inline may be our issue.. I believe we were running 1.1.3 or something of the like. Is there a quick guide on how to update this script and it's java functions on a mgmt gateway? 

`web_api_show_package_original.sh -k policy_name_here`

**Comment by chkp-rdecker** [comment]
Of course.
