### ISSUE TITLE
Tool exports Objects that are referenced only

### ISSUE THREAD

**Issue by hb9cwp** [CheckPointSW/ShowPolicyPackage#11]
When running web_api_show_package-jar-with-dependencies.jar on a management server R80.20 (see below), host and network objects appear only in the HTML Web pages if these objects are used somewhere, for example in a rule.

If such objects are not referenced yet, then they are not listed in the host or network pages.

The version of the tool that comes with R80.20 does not yet have support for options such as -c,  --show-membership, or --dereference-group-members. Therefore, I can not test if they would make unreferenced object appear in the the HTML pages.

[Expert@checkpoint:0]# clish
checkpoint> sh
checkpoint> show ver
checkpoint> show version all
Product version Check Point Gaia R80.20
OS build 14
OS kernel version 3.10.0-693cpx86_64
OS edition 64-bit
checkpoint>

**Comment by incubenet** [comment]
When will it be updated?
