### ISSUE TITLE
Issue regard Character set

### ISSUE THREAD

**Issue by incubenet** [CheckPointSW/ShowPolicyPackage#12]
Hi,

I'm Check Point Partner SE.
When we run the tool, the 2 bytes character is shown abnormally like the below.
![image](https://user-images.githubusercontent.com/35084285/55056656-0a5c6300-50aa-11e9-8a38-096fed08b4b8.png)

Can I request you to modify this?

**Comment by chkp-amiads** [comment]
Hi @incubenet , thanks for your feedback, we will open issue on our system and will update when resolved.

**Comment by incubenet** [comment]
When will it be updated?

**Comment by incubenet** [comment]
> Hi @incubenet , thanks for your feedback, we will open issue on our system and will update when resolved.

When will it be updated?

**Comment by incubenet** [comment]
When will it be updated?

**Comment by chkp-amiads** [comment]
Hi @incubenet , we added it to our stack. Investigation wasn't started yet. Will be started by EO April and then i will have accurate ETA for fix.

**Comment by incubenet** [comment]
Is "EO" End of April?
I hope to be fixed ASAP.
Thank you.

**Comment by chkp-amiads** [comment]
Yes EO == End of.
As i wrote, since we have other issues open, we will investigate it by EO April, then i will have ETA.

**Comment by chkp-amiads** [comment]
@incubenet , we just merged a fix for that issue.

**Comment by incubenet** [comment]
Where can I download merged file?

**Comment by incubenet** [comment]
@chkp-amiads , Where can I download merged file?
I cannot find changed web_api_show_package-jar-with-dependencies.jar file.

**Comment by incubenet** [comment]
@chkp-amiads , Is there any update?

**Comment by chkp-amiads** [comment]
@incubenet , we didn't create new release with new jar, we just fixed the code, i will make sure we will do that as well and update when done.

**Comment by incubenet** [comment]
@chkp-amiads , Then, Should I wait for it until next release?

**Comment by incubenet** [comment]
@chkp-amiads , I mean how I can apply the modified code.

**Comment by chkp-amiads** [comment]
You can download the code and compile it on your end, then you will have jar ready. If you don't have JDK installed, you can wait to our next release. Will prepare it in the next few days.

**Comment by incubenet** [comment]
@chkp-amiads , I would like to know how to compile the code. I'm not sure even though I checked the "Build Instruction". Would you please help me more details?

**Comment by incubenet** [comment]
How long does it take for release?

**Comment by chkp-yaelg** [comment]
Hi @incubenet 
I just released the new version, you can download it now from [here](https://github.com/CheckPointSW/ShowPolicyPackage/releases/tag/v2.0.3)

**Comment by incubenet** [comment]
@chkp-yaelg , I downloaded the new version and test it, but there is still character set issue.
Would you check this again?
![character set](https://user-images.githubusercontent.com/35084285/58080397-1a964780-7bee-11e9-8904-4aa84e63c815.JPG)

**Comment by chkp-yaelg** [comment]
@incubenet , please try to add this flag to your command: ```-Dfile.encoding=UTF-8```

the command should look like that:
``` java -Dfile.encoding=UTF-8 -jar web_api_show_package-jar-with-dependencies.jar ...```

**Comment by incubenet** [comment]
Thank you, it is working well.
I hope to be added option "web_api_show_package.sh"
