### ISSUE TITLE
the members section of Object Group show uid instead of name of member object

### ISSUE THREAD

**Issue by lpupillo** [CheckPointSW/ShowPolicyPackage#15]
the string associated to the href is the uid of the object instead of object name

**Comment by chkp-amiads** [comment]
Thanks for your feedback, we will work on fixing it. We will update this thread when fix will be delivered.

**Comment by chkp-amiads** [comment]
@lpupillo , please see this commit https://github.com/CheckPointSW/ShowPolicyPackage/commit/0d546d493fff6b63afcd038e2c0c30e03dd1635d .
