### ISSUE TITLE
Why was the -t template option removed? 

### ISSUE THREAD

**Issue by burgerzoid** [CheckPointSW/ShowPolicyPackage#17]
A question, not a bug. v2.0.0 had the change "Deprecated custom templates path flag (-t) was removed". 

Would be very useful to have custom templates, so changes were not overwritten on upgrade. Why was that option removed? Are there any plans to re-add it?

**Comment by burgerzoid** [comment]
Edited the html files in $MDS_FWDIR/api/samples/conf/ and those changes are not in the HTML output. Does it read template files from that directory? Does something have to be bounced to pick up changes?

**Comment by chkp-niram** [comment]
Hey @burgerzoid , the custom templates feature was removed as it wasn't compatible with important changes that were introduced to the tool to ensure data integrity and stability.
Right now we do not plan to add it in future releases as the same issues may rise.

**Comment by chkp-niram** [comment]
Since it's not currently planned to restore this option, i'm closing the issue for now. If there are further questions feel free to open another issue.
