### ISSUE TITLE
Wrong encoding in output HTML file when using cyrillic symbols in objects

### ISSUE THREAD

**Issue by dexion** [CheckPointSW/ShowPolicyPackage#19]
When I run `jar` like 
`java -jar web_api_show_package.jar -m <IP> -u <USER> -p <Password>`

I've got files with wrong encoding because in policy and objects comment cyrillic symbols are used. For workaround bout it I preferred `java **-Dfile.encoding=UTF-8** -jar web_api_show_package.jar -m <IP> -u <USER> -p <Password>`

I think it should be in main sources and not in java's VM configs.

**Comment by chkp-yaelg** [comment]
Hi @dexion ,
From our investigation this must be part of the command line.
If you don't want to use this every time that you execute the tool, you can edit the _web_api_show_package.sh_ file that found in _$MDS_FWDIR/scripts/web_api_show_package.sh_ on your machine.

Please keep sharing your feedback with us while using our repositories. In addition, as it is an open source, we encourage you to contribute and suggest code fixes/improvements in the future.
