### ISSUE TITLE
Problem with tool exporting under VS

### ISSUE THREAD

**Issue by wizzolo** [CheckPointSW/ShowPolicyPackage#25]
Hi all,

i've some issue under some VS, the exported file *.tar.gz contains empty file. in other VS work well. 

Below an example

Example
$MDS_FWDIR/scripts/web_api_show_package.sh -k XXXX -d YYY

Script finished running with warnings!
Result file location: show_package-2022-04-27_10-50-50.tar.gz

Could you help me please to find the problem ?

Regards
W.

**Comment by chkp-edenbr** [comment]
Hi,

Please open a ticket to Check Point Support.

Thanks
