### ISSUE TITLE
Exporting HTML group problem with not ip address

### ISSUE THREAD

**Issue by wizzolo** [CheckPointSW/ShowPolicyPackage#26]
Hi,

after using your tool, some group contains just a list of UID not the ip address, sometimes just few ip and UID

Below the example

Name:Test-group 
uid:	ffff-ffff-ffff-ffff-ffffffffffff
name:	test-group
type:	group
domain:	
uid:	ffff-ffff-ffff-ffff-ffffffffffff
name:	Global
domain-type:	global domain
color:	black
comments:	
groups:	[Empty array]
icon:	General/group
members:	
#0	ffffffff-ffff-ffff-ffff-ffffffffffff
#1    ffffffff-........

Checkpoint R81.10 VSX
Thank you

W.

**Comment by chkp-edenbr** [comment]
Hi,

Please open a ticket to Check Point Support.

Thanks
