### ISSUE TITLE
Configuration Export Error

### ISSUE THREAD

**Issue by sidantaa** [CheckPointSW/ShowPolicyPackage#30]
Hi ,

We are trying to migrate from existing Checkpoint R81.10 firewall to Paloalto. We are using Expedition tool for the same. But getting error while exporting the configuration package.  There was fingerprint issue earlier as: _Fingerprint was't approved. The fingerprint doesn't match to the fingerprints from the 'api fingerprint' command .Script stopped running due to severe error!_   . We dealt with this using **-b**  and after this we faced the following issue:

We tried to export the  configuration packages using **[V2.0.6](https://github.com/CheckPointSW/ShowPolicyPackage/releases/tag/V2.0.6)** and got error:

Exception in thread "main" java.lang.NullPointerException
at com.checkpoint.mgmt_api.objects.PolicyPackage.toJson(PolicyPackage.java:79)
at com.checkpoint.mgmt_api.objects.IndexView.toJson(IndexView.java:64)
at com.checkpoint.mgmt_api.examples.ShowPackageTool.buildIndexHtmlPage(ShowPackageTool.java:1606)
at com.checkpoint.mgmt_api.examples.ShowPackageTool.main(ShowPackageTool.java:184)

Later on, we tried using version **[V2.0.5](https://github.com/CheckPointSW/ShowPolicyPackage/releases/tag/v2.0.5)**:

It worked and package was displayed as: **show_package-2022-12-26_12-59-34.tar.gz**  by using command _java -jar web_api_show_package-jar-with-dependencies.jar -v_ and at this time file size is about ~_397 KB_

Later on after using the command:   _java -jar web_api_show_package-jar-with-dependencies.jar -k <PACKAGE NAME> -d <DOMAIN NAME>_ ; file size got reduced to 10KB.

We tried importing the package to migration tool. After conversion, objects, policies, NAT ,zones etc. nothing got reflected. Seems like whole configuration file is not exported.

Note: Checkpoint have suggested to use a very latest package version but .jar file is not available yet for the version **[v2.1.0](https://github.com/CheckPointSW/ShowPolicyPackage/releases/tag/v2.1.0)**  . Also we got error on V2.0.6 and using V2.0.5 didn't work as expected. 

Please, assist me on this.

**Comment by chkp-edenbr** [comment]
Hi @sidantaa,
We've uploaded the jar to the released version v2.1.0.
If the issue proceeds please open a TAC ticket.

Thanks,
Eden

**Comment by sidantaa** [comment]
> Hi @sidantaa, We've uploaded the jar to the released version v2.1.0. If the issue proceeds please open a TAC ticket.
> 
> Thanks, Eden

Thanks for the file. 

Thanks,
Sudip
