### ISSUE TITLE
Running the tool on exported files instead of connecting to Management?

### ISSUE THREAD

**Issue by thefunkygibbon** [CheckPointSW/ShowPolicyPackage#32]
Is there a way to run this on the exported files from a gateway (or management) rather than having to have direct connectivity to it?

If not, please consider this as an RFE. 

Example usecase:  have a dead management server, need to be able to visualise the running rulebase etc that is on the gateway so that can recreate it on a new management server, manually.

**Comment by chkp-edenbr** [comment]
Hi @thefunkygibbon ,
This isn't the purpose of the tool since it relies on the Management API.
Regards
