### ISSUE TITLE
Invalid json output

### ISSUE THREAD

**Issue by tomkopchak** [CheckPointSW/ShowPolicyPackage#4]
Tool produces invalid json files - they are missing the [] around the data, which causes parsing issues when attempting to use them in another application. 

We were able to work around this by doing the following:
(echo -n "[" ; cat Standard_objects.json; echo "]") | jq .

**Comment by CheckPoint-APIs-Team** [comment]
Thanks for the input.
We will review the code and fix it.

**Comment by tomkopchak** [comment]
Thank you!

**Comment by chkp-eugeneg** [comment]
Fixed, see #7
