### ISSUE TITLE
12h timestamp in output filename

### ISSUE THREAD

**Issue by gitajt** [CheckPointSW/ShowPolicyPackage#5]
formatDate should be assigned thus:
SimpleDateFormat formatDate = new SimpleDateFormat("YYYY-MM-dd_HH-mm-ss");

to create a 24h timestamp as per the README.md

**Comment by chkp-rdecker** [comment]
Right, will be fixed.
Thank you.

**Comment by chkp-eugeneg** [comment]
Fixed, see pull request #8
